version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y git
      - node -v
      - npm install -g cdk
      - npm install
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Let do CDK Synth...
      - cdk synth -c stage=dev
