version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - node -v
      - npm install
  pre_build:
    commands:
      - echo Let do CDK Synth...
      - cdk synth -c stage=dev
