name: Semantic release tag

on:
  push:
    branches:
      - master
      - test

jobs:
  build:
    name: checkout-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npx semantic-release --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
