name: Sygna Semantic Release

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - test
  push:
    branches:
      - dev

jobs:
  build:
    name: checkout-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: conditional-skip-ci
        run: echo "check if skip ci existed"
        if: "!contains(github.event.head_commit.message, '[skip ci]')"

      - name: conditional-headerWith-Merge
        run: echo "check if Header commit message with Merge existed"
        if: "!startsWith(github.event.head_commit.message, 'Merge')"

      - name: Install NPM
        run: |
          npm install

      - name: Semantic Release
        id: semantic
        uses: codfish/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #- name: Semantic Release
      #  uses: actions/setup-node@v1
      #  with:
      #    node-version: "12.x"
      #  run: |
      #    npm install
      #    npx semantic-release --no-ci
      #  env:
      #    GH_ACTIONS: true
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
